export const jobsList = {
  "ai-data-evaluator": {
    title: "AI Data Annotator & Quality Evaluator (Generalist)",
    hourlyRate: "$20/hr",
    overview: "We are seeking generalist AI Data Annotators to evaluate, rate, and improve the quality of responses generated by large language models. Your insights directly train the next generation of artificial intelligence.",
    requirements: [
      "Excellent written communication skills in English",
      "Strong analytical thinking and attention to detail",
      "Reliable internet connection and laptop/computer",
      "Ability to follow complex annotation instructions precisely"
    ],
    workflow: [
      "Analyze a given prompt or user instruction.",
      "Review up to 4 different AI-generated responses side-by-side.",
      "Identify factual errors, logical flaws, or tone issues.",
      "Rate the responses based on accuracy, helpfulness, and safety.",
      "Write a brief justification explaining your ratings."
    ]
  },
  "fact-checker": {
    title: "AI Fact-Checking & Citation Verifier",
    hourlyRate: "$23/hr",
    overview: "Join us as a Fact-Checking Specialist to combat AI 'hallucinations'. You will audit deep informational responses generated by AI models, cross-referencing their claims with live sources, databases, and research materials to ensure absolute factual integrity.",
    requirements: [
      "Exceptional research and internet sleuthing skills",
      "Skeptical, detail-oriented mindset—nothing gets past you",
      "Strong technical reading comprehension",
      "Experience in journalism, academic writing, or auditing is a plus"
    ],
    workflow: [
      "Receive an AI-generated essay, report, or historical summary.",
      "Extract every hard claim, statistic, date, and historical quote.",
      "Cross-reference those data points using authoritative online sources and provided literature.",
      "Flag false data, misleading frames, or unverified claims.",
      "Correct the incorrect statements and document your source links."
    ]
  },
  "creative-evaluator": {
    title: "Creative Writing & Tone Synthesis Evaluator",
    hourlyRate: "$21/hr",
    overview: "Help large language models develop personality, nuance, and artistic flair. In this role, you will evaluate creative copy—ranging from poetry and scripts to marketing emails and brand stories—grading how well the AI captures human emotion and complex constraints.",
    requirements: [
      "Background in creative writing, English literature, marketing, or copywriting",
      "Deep understanding of voice, tone, pacing, and emotional resonance",
      "Ability to critique abstract writing concepts clearly",
      "Flawless command of English idioms and stylistic nuances"
    ],
    workflow: [
      "Review a creative writing prompt (e.g., 'Write a melancholy poem about a lighthouse in the style of Emily Dickinson').",
      "Analyze multiple AI literary submissions against the prompt parameters.",
      "Grade the structural rhythm, rhyme choices, emotional impact, and tone consistency.",
      "Provide constructive feedback outlining why a human reader would find a draft authentic or robotic.",
      "Rewrite weak sentences or clumsy stanzas to model perfect performance."
    ]
  },
  "prompt-fidelity-evaluator": {
    title: "Text-to-Image Prompt Fidelity Evaluator",
    hourlyRate: "$22/hr",
    overview: "Work on the cutting edge of computer vision and multi-modal AI. You will judge how accurately leading text-to-image generator models translate complex descriptive prompts into high-quality visual renderings.",
    requirements: [
      "Strong visual literacy and an eye for physical composition/layouts",
      "Ability to notice subtle mismatches between written descriptions and visual outputs",
      "Familiarity with tracking spatial relationships (e.g., 'under', 'to the left of', 'in the background')",
      "No graphic design experience required, but an appreciation for visual detail is a must"
    ],
    workflow: [
      "Examine a highly specific text prompt containing multiple subjects, lighting styles, and layouts.",
      "Review 2 to 4 AI-generated image outputs generated from that prompt.",
      "Verify if every single object, color, text element, and spatial positioning requested is present.",
      "Identify visual defects (such as distorted anatomy, floating objects, or layout clipping).",
      "Submit ratings determining which model best followed the spirit and text of the prompt."
    ]
  }
};
