export const jobsList = {
  "ai-data-annotator-quality-evaluator-generalist": {
    title: "AI Data Annotator & Quality Evaluator (Generalist)",
    hourlyRate: "$20/hr",
    isOffPlatform: true,
    overview: "We are seeking generalist AI Data Annotators to evaluate, rate, and improve the quality of responses generated by large language models. Your insights directly train the next generation of artificial intelligence models. Please note that while applications are handled here, the underlying data curation tasks will be completed off the OceanSourceAI website on secure client workspace systems.",
    requirements: [
      "Excellent written and reading communication skills in English",
      "Strong analytical thinking, critical problem solving, and strict attention to detail",
      "Reliable high-speed internet connection and a dedicated desktop/laptop computer",
      "Ability to follow complex, multi-tiered annotation instructions precisely without deviation"
    ],
    workflow: [
      "Analyze a given complex user instruction prompt or scenario constraint.",
      "Review up to 4 distinct AI-generated responses side-by-side in real time.",
      "Identify subtle factual errors, logical contradictions, structural flaws, or tone issues.",
      "Rate the responses objectively based on accuracy, overall helpfulness, style compliance, and safety rules.",
      "Write a comprehensive markdown justification explaining your precise ratings."
    ]
  },
  "ai-fact-checking-citation-verifier": {
    title: "AI Fact-Checking & Citation Verifier",
    hourlyRate: "$23/hr",
    isOffPlatform: true,
    overview: "Join our specialization team as a Fact-Checking Specialist to combat deep AI 'hallucinations'. You will audit deep informational responses generated by AI models, cross-referencing their claims with live digital networks, authoritative academic databases, and reference literature to ensure absolute factual integrity. All actual verification projects will be completed off the OceanSourceAI website using sandboxed partner platforms.",
    requirements: [
      "Exceptional research, investigative cross-referencing, and internet sleuthing skills",
      "Skeptical, detail-oriented mindset—nothing gets past your screening",
      "Strong technical reading comprehension and speed-reading capacity",
      "Prior experience in journalism, legal auditing, academic research, or proofreading is heavily preferred"
    ],
    workflow: [
      "Receive an AI-generated deep essay, technical report, or complex historical summary.",
      "Isolate and extract every hard claim, numerical statistic, historical date, and quoted reference.",
      "Cross-reference those data points using authoritative primary online sources and provided journals.",
      "Flag false data elements, misleading contextual frames, or completely unverified claims.",
      "Correct the incorrect statements and document your authoritative source links explicitly."
    ]
  },
  "creative-writing-tone-synthesis-evaluator": {
    title: "Creative Writing & Tone Synthesis Evaluator",
    hourlyRate: "$21/hr",
    isOffPlatform: true,
    overview: "Help large language models develop human personality, nuance, wit, and artistic flair. In this role, you will evaluate highly creative copy—ranging from poetry and fictional scripts to marketing campaigns and brand stories—grading how well the AI captures human emotion. Production projects will be completed off the OceanSourceAI website within client-managed workspaces.",
    requirements: [
      "Background or degree in creative writing, English literature, marketing, or copywriting",
      "Deep abstract understanding of voice, tone, rhythmic pacing, and emotional resonance",
      "Ability to critique abstract writing concepts clearly with structured feedback summaries",
      "Flawless command of English idioms, cultural metaphors, and stylistic nuances"
    ],
    workflow: [
      "Review a complex creative writing prompt containing unique constraints (e.g. style of specific authors).",
      "Analyze multiple competitive AI literary submissions against the prompt parameters.",
      "Grade the structural rhythm, rhyme choices, overall emotional impact, and tone consistency.",
      "Provide constructive feedback outlining why a human reader would find a draft authentic or mechanical.",
      "Rewrite weak sentences or clumsy stanzas to model perfect performance metrics."
    ]
  },
  "text-to-image-prompt-fidelity-evaluator": {
    title: "Text-to-Image Prompt Fidelity Evaluator",
    hourlyRate: "$22/hr",
    isOffPlatform: true,
    overview: "Work on the cutting edge of computer vision and multi-modal AI systems. You will judge how accurately leading text-to-image generator models translate complex descriptive prompt texts into high-quality visual renderings. Production evaluation tracks are completed off the OceanSourceAI website on secure imaging networks.",
    requirements: [
      "Strong visual literacy and an exceptional eye for physical composition, perspective, and layouts",
      "Ability to notice subtle mismatches between written parameters and spatial visual outputs",
      "Familiarity with tracking complex spatial relationships (e.g., positioning, foreground relative to background)",
      "No graphic design experience required, but a strong appreciation for microscopic visual detail is a must"
    ],
    workflow: [
      "Examine a highly specific text prompt containing multiple subjects, lighting styles, and spatial layouts.",
      "Review 2 to 4 AI-generated image outputs generated from that identical text prompt.",
      "Verify if every single object, color asset, text element, and spatial positioning requested is present.",
      "Identify visual defects (such as distorted anatomy, floating objects, clipping, or lighting anomalies).",
      "Submit comprehensive ratings determining which model best followed the layout instructions."
    ]
  },
  "multi-turn-chatbot-safety-red-teamer": {
    title: "Multi-Turn Chatbot Safety Red-Teamer",
    hourlyRate: "$24/hr",
    isOffPlatform: true,
    overview: "Intentionally probe, trick, and 'stress-test' advanced conversational AI models to identify security loopholes, structural biases, or safety filter bypasses before public release. These sensitive testing projects are securely isolated and will be completed off the OceanSourceAI website.",
    requirements: [
      "Creative, adversarial mindset—thinking logically like an ethical hacker or exploit finder",
      "Strong understanding of conversational manipulation, social engineering tricks, and phrasing nuances",
      "Familiarity with online safety, moderation principles, or trust and safety enterprise policies",
      "Excellent documentation skills to report precise step-by-step vulnerabilities discovered"
    ],
    workflow: [
      "Develop creative, multi-step conversational attack vectors designed to bypass standard AI safety walls.",
      "Engage the AI chatbot in complex, adversarial text exchanges to coax it into generating restricted outputs.",
      "Document instances where the AI successfully resists manipulation versus where it slips up.",
      "Categorize the severity of safety leaks (e.g., malicious script writing, unverified legal/medical advice).",
      "Provide actionable feedback reports on how to patch the underlying model vulnerability."
    ]
  },
  "logical-reasoning-core-math-grader": {
    title: "Logical Reasoning & Core Math Grader",
    hourlyRate: "$25/hr",
    isOffPlatform: true,
    overview: "Review, evaluate, and correct the step-by-step mathematical reasoning and logical workflows of advanced problem-solving AI models to improve computational accuracy. Live grading workflows are delivered and will be completed off the OceanSourceAI website using custom math editors.",
    requirements: [
      "Strong foundational skills in mathematics, algebra, logic, proofs, or discrete reasoning models",
      "Ability to instantly spot micro-errors in sequential arithmetic or step-by-step derivations",
      "Extreme patience when reading through long, dense logical proofs and algorithmic expressions",
      "Background in STEM tutoring, engineering, computer science, or academic education is highly valued"
    ],
    workflow: [
      "Examine a high-school or introductory college-level word problem submitted to the AI.",
      "Trace through every individual row of calculation or deductive leap the AI generates to solve it.",
      "Pinpoint the exact step where the calculation or logic diverges from mathematical truth.",
      "Write a precise explanation detailing the flaw in the model's logic tree using clear breakdowns.",
      "Submit the verified, perfectly executed step-by-step correction to train the training system."
    ]
  },
  "language-translation-localization-auditor": {
    title: "Language Translation & Localization Auditor",
    hourlyRate: "$23/hr",
    isOffPlatform: true,
    overview: "Evaluate machine-translated materials for native flow, regional idioms, cultural context, and localized nuances to move text models beyond stiff literal word-for-word interpretations. Auditing files will be completed off the OceanSourceAI website on localized platforms.",
    requirements: [
      "Native or bilingual fluency in English plus at least one major secondary language tracking",
      "Deep understanding of localized slang, regional metaphors, and cultural taboos",
      "Excellent proofreading, grammar, and syntax grading capabilities in both languages",
      "Prior localization, localization testing, or freelance translation work is a massive asset"
    ],
    workflow: [
      "Read a source text along with up to three AI-generated translations in your target language side-by-side.",
      "Evaluate the text for mechanical accuracy (grammar, spelling) and tonal localization patterns.",
      "Flag phrasing that feels unnatural, overly formal, or contextually inappropriate to a native speaker.",
      "Score the translations on clarity, intent retention, and stylistic flow metrics.",
      "Provide the ideal native phrasing adjustments directly into the localization grading portal."
    ]
  },
  "image-description-alt-text-writer": {
    title: "Image Description & Alt-Text Writer",
    hourlyRate: "$20/hr",
    isOffPlatform: true,
    overview: "Produce crystal-clear, objective, and highly descriptive text breakdowns of physical scenes, charts, and graphics to feed multi-modal vision training pipelines. Data entry and asset analysis will be completed off the OceanSourceAI website on proprietary imaging infrastructure.",
    requirements: [
      "Strong descriptive vocabulary with zero reliance on filler words or ambiguous terms",
      "Ability to translate complex graphical data or cluttered visual images into highly structured text lists",
      "Strong spatial understanding of descriptive focus fields (foreground, background, focal points)",
      "Reliable track record with highly repetitive, detail-heavy text curation workflows"
    ],
    workflow: [
      "Analyze an un-tagged visual element (photograph, interface mock-up, or textbook diagram).",
      "Write a meticulously organized textual summary capturing all visible elements, textures, colors, and layout.",
      "Extract and transcribe any textual or numeric data embedded inside the visual asset.",
      "Ensure personal assumptions, artistic interpretations, or emotional biases are excluded from descriptions.",
      "Format the output text to meet strict accessibility and machine-learning ingestion standards."
    ]
  },
  "video-action-temporal-segmentation-tagger": {
    title: "Video Action & Temporal Segmentation Tagger",
    hourlyRate: "$22/hr",
    isOffPlatform: true,
    overview: "Audit and frame-tag raw video footage to teach kinetic AI systems to recognize physical dynamics, objects shifting, and human activities down to the millisecond. This visual task will be completed off the OceanSourceAI website via professional video canvas streaming setups.",
    requirements: [
      "High visual endurance for analyzing continuous video playbacks frame-by-frame over extended sessions",
      "Meticulous accuracy when working with timeline adjustments and hyper-precise timestamps",
      "Comfortable learning and adapting to custom video annotation software tools quickly",
      "Access to a high-speed internet connection for streaming continuous 4K video frames without buffer"
    ],
    workflow: [
      "Load a designated raw video asset within the interactive cloud platform workspace environment.",
      "Locate precise timestamps where a predefined physical activity or event initiates and concludes.",
      "Draw accurate 2D/3D bounding boxes around human entities or moving objects across video frames.",
      "Label environmental triggers, lighting modifications, or camera angles based on precise project rules.",
      "Validate the sequence timing maps to guarantee error-free injection into video-generation models."
    ]
  },
  "audio-transcription-accent-diarization": {
    title: "Audio Transcription & Accent Diarization",
    hourlyRate: "$21/hr",
    isOffPlatform: true,
    overview: "Transcribe audio materials from challenging environments to clean up auditory interference filters and help models parse unique regional accents. Transcription sequences will be completed off the OceanSourceAI website on audio streaming nodes.",
    requirements: [
      "Impeccable acoustic perception and sharp auditory processing faculties",
      "Deep familiarity with distinct English regional dialects, speed variations, and slurred phrasing patterns",
      "Fast, high-accuracy typing speeds accompanied by clean grammatical syntax formatting structures",
      "Prior transcription, transcription review, or closed-captioning experience is highly preferred"
    ],
    workflow: [
      "Listen closely to complex audio recordings featuring background murmurs, ambient sound, or multiple speakers.",
      "Type verbatim text files detailing spoken content, omitting no stutters, filler words, or colloquial expressions.",
      "Apply accurate speaker tags separating who is speaking throughout the conversation flow.",
      "Timestamp muffled words or unintelligible segments according to project guidelines.",
      "Verify the final output manuscript matches the underlying waveform perfectly."
    ]
  },
  "ui-ux-front-end-layout-evaluator": {
    title: "UI/UX Front-End Layout Evaluator",
    hourlyRate: "$24/hr",
    isOffPlatform: true,
    overview: "Examine visual front-end layouts generated by design LLMs, flagging rendering alignment flaws, responsive design bugs, and structural flaws. Interactive checking tasks will be completed off the OceanSourceAI website inside sandbox design viewers.",
    requirements: [
      "Basic structural understanding of modern web layout principles (Flexbox, Grid, CSS styling properties)",
      "Sharp visual eye for padding imbalances, overlapping text blocks, and micro-alignment issues",
      "Familiarity with viewing apps across varying viewport widths (mobile vs. tablet vs. desktop configurations)",
      "Clear communication style when detailing structural bugs to a technical platform pipeline"
    ],
    workflow: [
      "Load an AI-generated interface mockup or interactive web preview panel inside your workspace console.",
      "Test responsive scaling limits by adjusting structural preview screen configurations.",
      "Locate clipping margins, illegible font sizes, broken image assets, or broken button states.",
      "Rate the structural adherence of the page against popular design systems and style guides.",
      "Document all visual bugs found with clear explanations of where the rendering failed."
    ]
  },
  "code-correction-optimization-grader": {
    title: "Code Correction & Optimization Grader",
    hourlyRate: "$35/hr",
    isOffPlatform: true,
    overview: "Audit code snippets generated by AI models, ensuring they run efficiently, follow clean coding patterns, and contain zero security holes. Engineering projects will be completed off the OceanSourceAI website inside remote corporate container runtimes.",
    requirements: [
      "Practical familiarity writing and debugging script logic in Python, JavaScript, or TypeScript structures",
      "Familiarity with tracking computational efficiency (Big O notation, memory allocations, system leaks)",
      "Ability to quickly spot security flaws like SQL injections, unhandled edge cases, or broken routines",
      "Enrolled in or graduated from a Computer Science, Data Science, or Software Engineering track"
    ],
    workflow: [
      "Analyze a code generation prompt alongside the code blocks generated by the model.",
      "Execute or trace the code mentally to confirm structural correctness and execution efficiency.",
      "Expose silent logic failures, algorithmic bugs, or inefficient loop declarations.",
      "Refactor faulty blocks into production-grade code that executes flawlessly.",
      "Provide a highly instructional markdown summary explaining the exact rationale behind your fix."
    ]
  },
  "legal-brief-contract-analysis-verifier": {
    title: "Legal Brief & Contract Analysis Verifier",
    hourlyRate: "$45/hr",
    isOffPlatform: true,
    overview: "Audit legal documentation summaries generated by text models to make sure critical clauses, precedents, and liabilities are perfectly accurately stated. Auditing processes will be completed off the OceanSourceAI website on encrypted compliance servers.",
    requirements: [
      "Currently enrolled in law school, paralegal training pipelines, or holding a formal JD / legal career background",
      "Deep understanding of commercial contracting language, indemnities, and legal briefs structures",
      "Incredible attention to micro-phrasing and contextual conditional expressions within bindings",
      "Absolute dedication to protecting informational integrity within highly regulated contexts"
    ],
    workflow: [
      "Read through an original full-length legal contract or court briefing document.",
      "Review the automated overview, clause extraction, or executive brief generated by the AI model.",
      "Verify that no core legal provisions, liabilities, or deadlines were warped or dropped by the script.",
      "Correct any misstatements or overly broad interpretations introduced by the model.",
      "Draft a structured explanation of the legal impact of the model's error."
    ]
  },
  "medical-information-health-verification-specialist": {
    title: "Medical Information & Health Verification Specialist",
    hourlyRate: "$48/hr",
    isOffPlatform: true,
    overview: "Audit health explanations, symptom overviews, and anatomical descriptions written by AI to verify they match up exactly with peer-reviewed clinical literature. Medical evaluations are heavily regulated and will be completed off the OceanSourceAI website on HIPPA-compliant servers.",
    requirements: [
      "Background or degree in healthcare, medicine, nursing, pharmacology, or biological research fields",
      "Familiarity navigating clinical trial directories, PubMed registries, and medical indexes smoothly",
      "Zero tolerance for scientific leaps, false diagnostic frameworks, or unverified claims text",
      "Ability to translate complex medical insights into clear, safe prose instructions for patients"
    ],
    workflow: [
      "Evaluate a user health query alongside the model's synthesized healthcare response text.",
      "Cross-check all scientific assertions, drug mechanism assertions, and anatomical summaries against clinical consensus.",
      "Flag any dangerous guidance, misidentified symptom mappings, or unverified health claims text blocks.",
      "Inject verified, safe contextual parameters to correct any medical inaccuracies found.",
      "Sign off on the clinical safety score of the reviewed training block."
    ]
  },
  "search-intent-e-commerce-relevance-rater": {
    title: "Search Intent & E-Commerce Relevance Rater",
    hourlyRate: "$20/hr",
    isOffPlatform: true,
    overview: "Evaluate semantic search queries against product results to rate whether an AI recommendation search tool understands exactly what the user is trying to find. Evaluation batches are delivered and will be completed off the OceanSourceAI website on custom marketplace evaluation grids.",
    requirements: [
      "Intuitive understanding of consumer search behaviors, intent pathways, and shopping preferences",
      "Strong analytical skills to separate primary search intent from secondary or accidental matching keywords",
      "Comfort handling rapid, high-volume review screens and categorical selections accurately",
      "Excellent logical grouping and organizational capabilities"
    ],
    workflow: [
      "Review a consumer search keyword or intent string input into an e-commerce platform matrix.",
      "Examine the product listing results, images, and descriptors surfaced by the search algorithm script.",
      "Determine if the results perfectly match, partially match, or completely miss what the user intended to locate.",
      "Categorize peripheral recommendations based on semantic relationships and product attributes.",
      "Log your intent accuracy evaluations to fine-tune the consumer recommendation algorithm."
    ]
  }
};
